PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE machines (id integer primary key autoincrement not null, ip text unique not null, hostname text,lastupdate datetime not null, room text default null);
CREATE TABLE hostnames (id integer primary key autoincrement not null, ip text not null, hostname text, time datetime not null);
CREATE TABLE uptime (id integer primary key autoincrement not null, ip text not null,  time datetime not null, uptime integer not null);
CREATE TABLE users (id integer primary key autoincrement not null, ip text not null,  time datetime not null, users text);
CREATE TABLE network (id integer primary key autoincrement not null, ip text not null, time datetime not null, netspeed integer);
CREATE TABLE load (id integer primary key autoincrement not null, ip text not null, time datetime not null, cpuload real not null, loadavg real not null, cores integer not null);
CREATE TABLE diskspace (id integer primary key autoincrement not null, ip text not null, time datetime not null, volume text not null, free real not null, total real not null);
COMMIT;
